var express = require('express');
var router = express.Router();

const itemList = [
  { 'id': 1, 'title': 'DevOps', 'description': 'DevOps is a set of practices that combine software development (Dev) and IT operations (Ops) to enhance collaboration, automation, and continuous integration and delivery.', 'reference': 'https://www.atlassian.com/devops#:~:text=DevOps%20is%20a%20set%20of,and%20collaboration%2C%20and%20technology%20automation.'},
  { 'id': 2, 'title': 'Agile', 'description': 'Agile is a project management and product development approach that focuses on iterative and incremental work delivery, emphasizing customer collaboration and adaptability.', 'reference': 'https://www.atlassian.com/devops#:~:text=DevOps%20is%20a%20set%20of,and%20collaboration%2C%20and%20technology%20automation.'},
  { 'id': 3, 'title': 'Microservices', 'description': 'Microservices is an architectural style that structures an application as a collection of loosely coupled services, allowing for easier development, scaling, and maintenance.', 'reference': 'https://www.bmc.com/blogs/devops-microservices/'},
  { 'id': 4, 'title': 'API ', 'description': 'API is the acronym for application programming interface — a software intermediary that allows two applications to talk to each other. APIs are an accessible way to extract and share data within and across organizations.', 'reference': 'https://www.mulesoft.com/resources/api/what-is-an-api#:~:text=API%20is%20the%20acronym%20for,data%20within%20and%20across%20organizations.'},
  { 'id': 5, 'title': 'Continuous Delivery/Continuous Integration', 'description': 'CI/CD stands for Continuous Integration and Continuous Delivery. It is a DevOps approach that involves frequent code integration, automated testing, and rapid deployment.', 'reference': 'https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts-continuous-delivery-integration.html'},
  { 'id': 6, 'title': 'DevSecOps', 'description': 'DevSecOps is a collaboration framework that expands the impact of DevOps by adding security practices to the software development and delivery process.', 'reference': 'https://www.dynatrace.com/monitoring/solutions/devsecops-ciso/?utm_source=google&utm_medium=cpc&utm_term=devsecops&utm_campaign=anz-appsec-application-security&utm_content=none&utm_campaign_id=11848445955&gclsrc=aw.ds&gclid=Cj0KCQjwn_OlBhDhARIsAG2y6zOntJ94C3Nf13rmIr_mavYFIkqSVmqOLmuEX0DBOy8ovqnBoN1q8VUaAutqEALw_wcB'},
  { 'id': 7, 'title': 'kanban', 'description': 'Kanban is a popular framework used to implement agile and DevOps software development. It requires real-time communication of capacity and full transparency of work.', 'reference': 'https://www.atlassian.com/agile/kanban#:~:text=Kanban%20is%20a%20popular%20framework,of%20work%20at%20any%20time.'},
  { 'id': 8, 'title': 'Pull Request', 'description': 'also referred to as a merge request is an event that takes place in software development when a contributor/developer is ready to begin the process of merging new code changes with the main project repository.', 'reference': 'https://www.pagerduty.com/resources/learn/what-is-a-pull-request/#:~:text=A%20pull%20request%20%E2%80%93%20also%20referred,with%20the%20main%20project%20repository.'},
  { 'id': 9, 'title': 'AWS', 'description': 'AWS (Amazon Web Services) is a cloud computing platform that offers a wide range of cloud services, including computing power, storage, and databases, among others.', 'reference': 'https://aws.amazon.com/what-is-aws/'},
  { 'id': 10, 'title': 'Infrastructure as Code (IaC)', 'description': 'IaC is a practice where infrastructure is defined and managed using code and version control, enabling automated and consistent provisioning of resources.', 'reference': 'https://www.hashicorp.com/resources/what-is-infrastructure-as-code'},
  { 'id': 11, 'title': 'Exploratory Testing', 'description': 'Exploratory testing is a dynamic and unscripted approach to software testing that focuses on uncovering defects, issues, and vulnerabilities in an application through real-time exploration', 'reference': 'https://www.atlassian.com/continuous-delivery/software-testing/exploratory-testing#:~:text=Exploratory%20testing%20is%20an%20approach,the%20scope%20of%20other%20tests.'},
  { 'id': 12, 'title': 'Microservices Architecture', 'description': 'A microservices architecture is a type of application architecture where the application is developed as a collection of services', 'reference': 'https://cloud.google.com/learn/what-is-microservices-architecture#:~:text=A%20microservices%20architecture%20is%20a,architecture%20diagrams%20and%20services%20independently.'},
  { 'id': 13, 'title': 'Deployment Pipeline', 'description': 'a deployment pipeline is a system of automated processes designed to quickly and accurately move new code additions and updates from version control to production', 'reference': 'https://www.pagerduty.com/resources/learn/what-is-a-deployment-pipeline/#:~:text=In%20software%20development%2C%20a%20deployment,from%20version%20control%20to%20production.'},
  { 'id': 14, 'title': 'Docker image', 'description': 'A Docker image is a file used to execute code in a Docker container. Docker images act as a set of instructions to build a Docker container, like a template.', 'reference': 'https://www.techtarget.com/searchitoperations/definition/Docker-image#:~:text=A%20Docker%20image%20is%20a,virtual%20machine%20(VM)%20environments.'},
  { 'id': 15, 'title': 'Containerization ', 'description': 'Containerization entails placing a software component and its environment, dependencies, and configuration, into an isolated unit called a container.', 'reference': 'https://www.aquasec.com/cloud-native-academy/docker-container/container-devops/#:~:text=What%20Does%20Containerization%20Mean%20for,%2Dpremises%20or%20cloud%2Dbased.'},
  { 'id': 16, 'title': 'Image', 'description': 'In computer science an image is an exact replica of the contents of a storage device (a hard disk drive or CD-ROM for example) stored on a second storage device.', 'reference': 'https://www.osti.gov/servlets/purl/1512856#:~:text=Page%2012-,DevOps%20Building,on%20a%20second%20storage%20device.'},
  { 'id': 17, 'title': 'lead time', 'description': 'Lead time helps measure how long it takes to deploy a release into a development, testing or production environment.', 'reference': 'https://www.software.com/devops-guides/lead-time'},
  { 'id': 18, 'title': 'Mean time to recovery (MTTR)', 'description': 'Mean time to recovery (MTTR) measures how long it takes to recover from a partial service interruption or total failure.', 'reference': 'https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=One%20of%20the%20critical%20DevOps,is%20in%20a%20deployable%20state.'},
  { 'id': 19, 'title': 'Version control', 'description': 'Version control, also known as source control, is one of the key tools used by successful DevOps teams for reducing development time and increasing the rate of successful deployments. Version control helps software engineering teams to collaborate at the speeds required by todays constantly shifting IT environment.', 'reference': 'https://www.bmc.com/blogs/devops-source-version-control/#:~:text=Version%20control%2C%20also%20known%20as,todays%20constantly%20shifting%20IT%20environment.'},
  { 'id': 20, 'title': 'Model-Based Testing', 'description': 'Model-based testing is an application of model-based design for designing and optionally also executing artifacts to perform software testing or system testing.', 'reference': 'https://en.wikipedia.org/wiki/Model-based_testing#:~:text=Model%2Dbased%20testing%20is%20an,strategies%20and%20a%20test%20environment.'},
  

];


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', items: itemList });
});

module.exports = router;
