var express = require('express');
var router = express.Router();

const itemList = [
  { 'id': 1, 'title': 'DevOps', 'description': 'DevOps is a set of practices that combine software development (Dev) and IT operations (Ops) to enhance collaboration, automation, and continuous integration and delivery.', 'reference': 'https://www.atlassian.com/devops#:~:text=DevOps%20is%20a%20set%20of,and%20collaboration%2C%20and%20technology%20automation.'},
  { 'id': 2, 'title': 'Agile', 'description': 'Agile is a project management and product development approach that focuses on iterative and incremental work delivery, emphasizing customer collaboration and adaptability.', 'reference': 'https://www.atlassian.com/devops#:~:text=DevOps%20is%20a%20set%20of,and%20collaboration%2C%20and%20technology%20automation.'},
  { 'id': 3, 'title': 'Microservices', 'description': 'Microservices is an architectural style that structures an application as a collection of loosely coupled services, allowing for easier development, scaling, and maintenance.', 'reference': 'https://www.bmc.com/blogs/devops-microservices/'},
  { 'id': 4, 'title': 'API ', 'description': 'API is the acronym for application programming interface — a software intermediary that allows two applications to talk to each other. APIs are an accessible way to extract and share data within and across organizations.', 'reference': 'https://www.mulesoft.com/resources/api/what-is-an-api#:~:text=API%20is%20the%20acronym%20for,data%20within%20and%20across%20organizations.'},
  { 'id': 5, 'title': 'Continuous Delivery/Continuous Integration', 'description': 'CI/CD stands for Continuous Integration and Continuous Delivery. It is a DevOps approach that involves frequent code integration, automated testing, and rapid deployment.', 'reference': 'https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts-continuous-delivery-integration.html'},
  { 'id': 6, 'title': 'DevSecOps', 'description': 'DevSecOps is a collaboration framework that expands the impact of DevOps by adding security practices to the software development and delivery process.', 'reference': 'https://www.dynatrace.com/monitoring/solutions/devsecops-ciso/?utm_source=google&utm_medium=cpc&utm_term=devsecops&utm_campaign=anz-appsec-application-security&utm_content=none&utm_campaign_id=11848445955&gclsrc=aw.ds&gclid=Cj0KCQjwn_OlBhDhARIsAG2y6zOntJ94C3Nf13rmIr_mavYFIkqSVmqOLmuEX0DBOy8ovqnBoN1q8VUaAutqEALw_wcB'},
  { 'id': 7, 'title': 'kanban', 'description': 'Kanban is a popular framework used to implement agile and DevOps software development. It requires real-time communication of capacity and full transparency of work.', 'reference': 'https://www.atlassian.com/agile/kanban#:~:text=Kanban%20is%20a%20popular%20framework,of%20work%20at%20any%20time.'},
  { 'id': 8, 'title': 'Pull Request', 'description': 'also referred to as a merge request is an event that takes place in software development when a contributor/developer is ready to begin the process of merging new code changes with the main project repository.', 'reference': 'https://www.pagerduty.com/resources/learn/what-is-a-pull-request/#:~:text=A%20pull%20request%20%E2%80%93%20also%20referred,with%20the%20main%20project%20repository.'},
  { 'id': 9, 'title': 'AWS', 'description': 'AWS (Amazon Web Services) is a cloud computing platform that offers a wide range of cloud services, including computing power, storage, and databases, among others.', 'reference': 'https://aws.amazon.com/what-is-aws/'},
  { 'id': 10, 'title': 'Infrastructure as Code (IaC)', 'description': 'IaC is a practice where infrastructure is defined and managed using code and version control, enabling automated and consistent provisioning of resources.', 'reference': 'https://www.hashicorp.com/resources/what-is-infrastructure-as-code'},
  { 'id': 11, 'title': 'Exploratory Testing', 'description': 'Exploratory testing is a dynamic and unscripted approach to software testing that focuses on uncovering defects, issues, and vulnerabilities in an application through real-time exploration', 'reference': 'https://www.atlassian.com/continuous-delivery/software-testing/exploratory-testing#:~:text=Exploratory%20testing%20is%20an%20approach,the%20scope%20of%20other%20tests.'},
  { 'id': 12, 'title': 'Microservices Architecture', 'description': 'A microservices architecture is a type of application architecture where the application is developed as a collection of services', 'reference': 'https://cloud.google.com/learn/what-is-microservices-architecture#:~:text=A%20microservices%20architecture%20is%20a,architecture%20diagrams%20and%20services%20independently.'},
  { 'id': 13, 'title': 'Deployment Pipeline', 'description': 'a deployment pipeline is a system of automated processes designed to quickly and accurately move new code additions and updates from version control to production', 'reference': 'https://www.pagerduty.com/resources/learn/what-is-a-deployment-pipeline/#:~:text=In%20software%20development%2C%20a%20deployment,from%20version%20control%20to%20production.'},
  { 'id': 14, 'title': 'Docker image', 'description': 'A Docker image is a file used to execute code in a Docker container. Docker images act as a set of instructions to build a Docker container, like a template.', 'reference': 'https://www.techtarget.com/searchitoperations/definition/Docker-image#:~:text=A%20Docker%20image%20is%20a,virtual%20machine%20(VM)%20environments.'},
  { 'id': 15, 'title': 'Containerization ', 'description': 'Containerization entails placing a software component and its environment, dependencies, and configuration, into an isolated unit called a container.', 'reference': 'https://www.aquasec.com/cloud-native-academy/docker-container/container-devops/#:~:text=What%20Does%20Containerization%20Mean%20for,%2Dpremises%20or%20cloud%2Dbased.'},
  { 'id': 16, 'title': 'Image', 'description': 'In computer science an image is an exact replica of the contents of a storage device (a hard disk drive or CD-ROM for example) stored on a second storage device.', 'reference': 'https://www.osti.gov/servlets/purl/1512856#:~:text=Page%2012-,DevOps%20Building,on%20a%20second%20storage%20device.'},
  { 'id': 17, 'title': 'lead time', 'description': 'Lead time helps measure how long it takes to deploy a release into a development, testing or production environment.', 'reference': 'https://www.software.com/devops-guides/lead-time'},
  { 'id': 18, 'title': 'Mean time to recovery (MTTR)', 'description': 'Mean time to recovery (MTTR) measures how long it takes to recover from a partial service interruption or total failure.', 'reference': 'https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=One%20of%20the%20critical%20DevOps,is%20in%20a%20deployable%20state.'},
  { 'id': 19, 'title': 'Version control', 'description': 'Version control, also known as source control, is one of the key tools used by successful DevOps teams for reducing development time and increasing the rate of successful deployments. Version control helps software engineering teams to collaborate at the speeds required by todays constantly shifting IT environment.', 'reference': 'https://www.bmc.com/blogs/devops-source-version-control/#:~:text=Version%20control%2C%20also%20known%20as,todays%20constantly%20shifting%20IT%20environment.'},
  { 'id': 20, 'title': 'Model-Based Testing', 'description': 'Model-based testing is an application of model-based design for designing and optionally also executing artifacts to perform software testing or system testing.', 'reference': 'https://en.wikipedia.org/wiki/Model-based_testing#:~:text=Model%2Dbased%20testing%20is%20an,strategies%20and%20a%20test%20environment.'},
  { 'id': 21, 'title': '.yam', 'description': 'YAML is a human-readable data-serialization language. It is commonly used for configuration files and in applications where data is being stored or transmitted.', 'reference': 'https://en.wikipedia.org/wiki/YAML'},
  { 'id': 22, 'title': 'docker-compose', 'description': 'Docker Compose is a tool that helps you define and share multi-container applications.', 'reference': 'https://docs.docker.com/get-started/08_using_compose/#:~:text=Docker%20Compose%20is%20a%20tool,or%20tear%20it%20all%20down.'},
  { 'id': 23, 'title': ' docker scout quickview', 'description': 'The docker scout quickview command displays a quick overview of an image. It displays a summary of the vulnerabilities in the image and the vulnerabilities from the base image. If available it also displays base image refresh and update recommendations.', 'reference': 'https://docs.docker.com/engine/reference/commandline/scout_quickview/'},
  { 'id': 24, 'title': 'Alpine', 'description': 'Docker Alpine is the “Dockerized” version of Alpine Linux,Docker Alpine is a popular choice for developers looking for a base image on which to create their own containerized apps', 'reference': 'https://sysdig.com/learn-cloud-native/container-security/what-is-docker-alpine/#:~:text=Docker%20Alpine%20is%20the%20%E2%80%9CDockerized,create%20their%20own%20containerized%20apps.'},
  { 'id': 25, 'title': 'Git fork', 'description': 'A fork in Git is simply a copy of an existing repository in which the new owner disconnects the codebase from previous committers.', 'reference': 'https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/command-line-GitHub-fork-CLI-terminal-shell#:~:text=A%20fork%20in%20Git%20is,that%20of%20the%20original%20project.'},
  { 'id': 26, 'title': 'Containers as a service (CaaS)', 'description': 'Containers as a service (CaaS) is a cloud service that allows software developers and IT departments to upload, organize, run, scale, manage and stop containers by using container-based virtualization.', 'reference': 'https://www.techtarget.com/searchitoperations/definition/Containers-as-a-Service-CaaS#:~:text=Containers%20as%20a%20service%20(CaaS)%20is%20a%20cloud%20service%20that,by%20using%20container%2Dbased%20virtualization.'},
  { 'id': 27, 'title': 'Continuous Deployment', 'description': 'Continuous deployment is a strategy in software development where code changes to an application are released automatically into the production environment.', 'reference': 'https://www.simplilearn.com/tutorials/devops-tutorial/continuous-delivery-and-continuous-deployment#:~:text=The%20practice%20of%20Modern%20Development,code%20changes%20frequently%20and%20safely.'},
  { 'id': 28, 'title': 'Configuration Management', 'description': 'DevOps configuration is the evolution and automation of the systems administration role, bringing automation to infrastructure management and deployment.', 'reference': 'https://www.atlassian.com/microservices/microservices-architecture/configuration-management#:~:text=DevOps%20configuration%20management&text=DevOps%20configuration%20is%20the%20evolution,the%20umbrella%20of%20software%20engineering.'},
  { 'id': 29, 'title': 'Continuous Testing', 'description': 'Continuous Testing refers to the execution of automated tests that are carried out at regular intervals every time code changes are made.', 'reference': 'https://www.browserstack.com/guide/continuous-testing-in-devops#:~:text=%E2%80%9CContinuous%20Testing%20refers%20to%20the,pushed%20to%20the%20code%20repository.%E2%80%9D'},
  { 'id': 30, 'title': 'Mean Time Between Failures (MTBF)', 'description': 'MTTR is used as a measure of the time it takes the DevOps team to recover from an issue during production.', 'reference': 'https://www.splunk.com/en_us/blog/learn/mttr-mean-time-to-repair.html?301=/en_us/data-insider/what-is-mean-time-to-repair.html#:~:text=What%20is%20MTTR%20in%20DevOps,from%20an%20issue%20during%20production.'},
  { 'id': 31, 'title': 'Jenkins ', 'description': 'Jenkins is an open source automation server. It helps automate the parts of software development related to building, testing, and deploying, facilitating continuous integration, and continuous delivery. It is a server-based system that runs in servlet containers such as Apache Tomcat.', 'reference': 'https://en.wikipedia.org/wiki/Jenkins_(software)'},
  { 'id': 32, 'title': 'RabbitMQ ', 'description': 'RabbitMQ is a widely used open-source message broker that helps in scaling the application by deploying a message queuing mechanism in between the two applications.', 'reference': 'https://hevodata.com/learn/rabbitmq-queue/#:~:text=RabbitMQ%20is%20a%20widely%20used,sends%20them%20to%20the%20consumer'},
  { 'id': 33, 'title': 'Docker', 'description': 'Docker is a software platform that allows you to build, test, and deploy applications quickly. Docker packages software into standardized units called containers that have everything the software needs to run including libraries, system tools, code, and runtime.', 'reference': 'https://aws.amazon.com/docker/'},
  { 'id': 34, 'title': 'Service Orchestration', 'description': 'Service orchestration is the execution of the operational and functional processes involved in designing, creating, and delivering an end-to-end service.', 'reference': 'https://www.ciena.com/insights/what-is/what-is-service-orchestration.html#:~:text=Service%20orchestration%20is%20the%20execution,end%2Dto%2Dend%20service.'},
  { 'id': 35, 'title': 'Continuous Improvement', 'description': 'Continuous improvement is an ongoing process of identifying, analyzing, and making incremental improvements to systems, processes, products, or services.', 'reference': 'https://kanbanize.com/lean-management/improvement/what-is-continuous-improvement'},
  { 'id': 36, 'title': 'Kubernetes Cluster', 'description': 'A Kubernetes cluster is a set of node machines for running containerized applications. At a minimum, a cluster contains a control plane and one or more compute machines, or nodes. ', 'reference': 'https://www.redhat.com/en/topics/containers/what-is-a-kubernetes-cluster'},
  { 'id': 37, 'title': 'Garbage Collection', 'description': 'Garbage collection is a collective term for the various mechanisms Kubernetes uses to clean up cluster resources. This allows the clean up of resources like the following:Terminated pods, Completed Jobs, Objects without owner references', 'reference': 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/'},
  { 'id': 38, 'title': 'Namespaces', 'description': 'Namespaces are used to keep resources separated. A company which uses 1 cluster but has multiple projects can use namespaces to split the cluster into virtual clusters, one for each project. Most commonly they would be used to separate environments such as production, testing, staging.', 'reference': 'https://devopswithkubernetes.com/part-2/2-organizing-a-cluster'},
  { 'id': 39, 'title': 'Kubectl', 'description': 'The Kubernetes command-line tool, kubectl, allows you to run commands against Kubernetes clusters. You can use kubectl to deploy applications, inspect and manage cluster resources, and view logs. ', 'reference': 'https://kubernetes.io/docs/tasks/tools/'},
  { 'id': 40, 'title': 'Kubernetes pod', 'description': 'A Kubernetes pod is a collection of one or more Linux® containers, and is the smallest unit of a Kubernetes application. Any given pod can be composed of multiple, tightly coupled containers (an advanced use case) or just a single container (a more common use case).', 'reference': 'https://www.redhat.com/en/topics/containers/what-is-kubernetes-pod#:~:text=Kubernetes%20patterns-,Overview,a%20more%20common%20use%20case).'},
  

];


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', items: itemList });
});

module.exports = router;
